// Life Optimizer
// Copyright (C) 2026 MILAN NIKOLIC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! Cantonal simple-tax scales imported from ESTV "Tarife" exports.
//!
//! GENERATED by `tools/import_estv_scales.py` -- do not edit by hand;
//! re-run the importer instead.
//!
//! Source: ESTV tax calculator Tarife exports (8 files):
//!   * `estv_scales_AG.xlsx`
//!   * `estv_scales_BS.xlsx`
//!   * `estv_scales_FR.xlsx`
//!   * `estv_scales_GE.xlsx`
//!   * `estv_scales_LU.xlsx`
//!   * `estv_scales_SH.xlsx`
//!   * `estv_scales_SO.xlsx`
//!   * `estv_scales_ZH.xlsx`
//!
//! `threshold` is the income level at which the band begins and `rate` is
//! that band's marginal rate as a fraction. The ESTV export expresses the
//! same schedule as band *widths* ("Für die nächsten CHF"); the importer
//! accumulates those widths into thresholds, which is an exact conversion
//! for the marginal structure.
//!
//! # Marital treatment is expressed in two different ways
//!
//! Cantons differ, and the two axes must not be applied together:
//!
//! * A canton publishing ONE scale (`Steuersubjekt = Alle`) expresses the
//!   marital difference through the **splitting factor**, which applies
//!   only to married taxpayers.
//! * A canton publishing SEPARATE scales per `Steuersubjekt` has already
//!   encoded the difference in the scale, so the splitting factor is
//!   `None` here and must not be applied on top.

use crate::federal_tax::FederalBracket;

/// One canton's imported simple-tax scale.
#[derive(Debug, Clone, Copy)]
pub struct BaseScale {
    pub canton_code: &'static str,
    /// Income-splitting divisor for MARRIED taxpayers, applied only when the
    /// canton publishes a single shared scale. `None` when marital status is
    /// already encoded in the separate `single`/`married` scales.
    pub splitting_factor_married: Option<f64>,
    /// Marginal bands for a single taxpayer.
    pub single: &'static [FederalBracket],
    /// Marginal bands for a married taxpayer.
    pub married: &'static [FederalBracket],
    /// True when the canton publishes one scale for all taxpayers.
    pub shared_scale: bool,
    /// The `Steuersubjekt` values present in the export, so an unexpected
    /// subject split is visible rather than silently merged.
    pub subjects: &'static [&'static str],
}

impl BaseScale {
    /// The bands that apply to the given marital status.
    pub fn brackets(&self, married: bool) -> &'static [FederalBracket] {
        if married { self.married } else { self.single }
    }

    /// The splitting factor to apply, which is only ever non-`None` for a
    /// married taxpayer on a shared scale.
    pub fn splitting_factor(&self, married: bool) -> Option<f64> {
        if married { self.splitting_factor_married } else { None }
    }
}

/// Simple-tax scale for canton AG, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const AG_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 4300.0, rate: 0.01 },
    FederalBracket { threshold: 8100.0, rate: 0.02 },
    FederalBracket { threshold: 12000.0, rate: 0.03 },
    FederalBracket { threshold: 16200.0, rate: 0.04 },
    FederalBracket { threshold: 20500.0, rate: 0.05 },
    FederalBracket { threshold: 25700.0, rate: 0.06 },
    FederalBracket { threshold: 33100.0, rate: 0.07 },
    FederalBracket { threshold: 41700.0, rate: 0.08 },
    FederalBracket { threshold: 51300.0, rate: 0.085 },
    FederalBracket { threshold: 63100.0, rate: 0.09 },
    FederalBracket { threshold: 74800.0, rate: 0.095 },
    FederalBracket { threshold: 110100.0, rate: 0.1 },
    FederalBracket { threshold: 176400.0, rate: 0.105 },
    FederalBracket { threshold: 352700.0, rate: 0.11 },
];

/// Simple-tax scale for canton AG, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const AG_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 4300.0, rate: 0.01 },
    FederalBracket { threshold: 8100.0, rate: 0.02 },
    FederalBracket { threshold: 12000.0, rate: 0.03 },
    FederalBracket { threshold: 16200.0, rate: 0.04 },
    FederalBracket { threshold: 20500.0, rate: 0.05 },
    FederalBracket { threshold: 25700.0, rate: 0.06 },
    FederalBracket { threshold: 33100.0, rate: 0.07 },
    FederalBracket { threshold: 41700.0, rate: 0.08 },
    FederalBracket { threshold: 51300.0, rate: 0.085 },
    FederalBracket { threshold: 63100.0, rate: 0.09 },
    FederalBracket { threshold: 74800.0, rate: 0.095 },
    FederalBracket { threshold: 110100.0, rate: 0.1 },
    FederalBracket { threshold: 176400.0, rate: 0.105 },
    FederalBracket { threshold: 352700.0, rate: 0.11 },
];

/// Simple-tax scale for canton BS, single taxpayer.
pub const BS_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.21 },
    FederalBracket { threshold: 0.0, rate: 0.2725 },
    FederalBracket { threshold: 212500.0, rate: 0.2825 },
];

/// Simple-tax scale for canton BS, married taxpayer.
pub const BS_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.21 },
    FederalBracket { threshold: 0.0, rate: 0.2725 },
    FederalBracket { threshold: 424900.0, rate: 0.2825 },
];

/// Simple-tax scale for canton FR, single taxpayer.
pub const FR_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 5199.0, rate: 0.01 },
    FederalBracket { threshold: 10399.0, rate: 0.041745000000000004 },
    FederalBracket { threshold: 27899.0, rate: 0.062139 },
    FederalBracket { threshold: 59299.0, rate: 0.08035199999999999 },
    FederalBracket { threshold: 107599.0, rate: 0.09104200000000001 },
    FederalBracket { threshold: 171399.0, rate: 0.099846 },
    FederalBracket { threshold: 248999.0, rate: 0.108662 },
    FederalBracket { threshold: 351099.0, rate: 0.117172 },
    FederalBracket { threshold: 479799.0, rate: 0.125355 },
    FederalBracket { threshold: 635799.0, rate: 0.131097 },
    FederalBracket { threshold: 816799.0, rate: 0.135 },
];

/// Simple-tax scale for canton FR, married taxpayer.
pub const FR_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 5199.0, rate: 0.01 },
    FederalBracket { threshold: 10399.0, rate: 0.01 },
    FederalBracket { threshold: 20899.0, rate: 0.041745000000000004 },
    FederalBracket { threshold: 55899.0, rate: 0.062139 },
    FederalBracket { threshold: 118699.0, rate: 0.08035199999999999 },
    FederalBracket { threshold: 215299.0, rate: 0.09104200000000001 },
    FederalBracket { threshold: 342899.0, rate: 0.099846 },
    FederalBracket { threshold: 498099.0, rate: 0.108662 },
    FederalBracket { threshold: 702299.0, rate: 0.117172 },
    FederalBracket { threshold: 959699.0, rate: 0.125355 },
    FederalBracket { threshold: 1271699.0, rate: 0.131097 },
    FederalBracket { threshold: 1633699.0, rate: 0.135 },
];

/// Simple-tax scale for canton GE, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const GE_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 0.0, rate: 0.073 },
    FederalBracket { threshold: 18700.0, rate: 0.08199999999999999 },
    FederalBracket { threshold: 41230.0, rate: 0.091 },
    FederalBracket { threshold: 66014.0, rate: 0.1 },
    FederalBracket { threshold: 93050.0, rate: 0.109 },
    FederalBracket { threshold: 122340.0, rate: 0.113 },
    FederalBracket { threshold: 157262.0, rate: 0.12300000000000001 },
    FederalBracket { threshold: 196690.0, rate: 0.128 },
    FederalBracket { threshold: 240625.0, rate: 0.132 },
    FederalBracket { threshold: 289066.0, rate: 0.142 },
    FederalBracket { threshold: 366796.0, rate: 0.15 },
    FederalBracket { threshold: 494093.0, rate: 0.156 },
    FederalBracket { threshold: 665324.0, rate: 0.158 },
    FederalBracket { threshold: 859086.0, rate: 0.16 },
    FederalBracket { threshold: 1136211.0, rate: 0.168 },
    FederalBracket { threshold: 1431361.0, rate: 0.17600000000000002 },
    FederalBracket { threshold: 1847049.0, rate: 0.18 },
];

/// Simple-tax scale for canton GE, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const GE_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 0.0, rate: 0.073 },
    FederalBracket { threshold: 18700.0, rate: 0.08199999999999999 },
    FederalBracket { threshold: 41230.0, rate: 0.091 },
    FederalBracket { threshold: 66014.0, rate: 0.1 },
    FederalBracket { threshold: 93050.0, rate: 0.109 },
    FederalBracket { threshold: 122340.0, rate: 0.113 },
    FederalBracket { threshold: 157262.0, rate: 0.12300000000000001 },
    FederalBracket { threshold: 196690.0, rate: 0.128 },
    FederalBracket { threshold: 240625.0, rate: 0.132 },
    FederalBracket { threshold: 289066.0, rate: 0.142 },
    FederalBracket { threshold: 366796.0, rate: 0.15 },
    FederalBracket { threshold: 494093.0, rate: 0.156 },
    FederalBracket { threshold: 665324.0, rate: 0.158 },
    FederalBracket { threshold: 859086.0, rate: 0.16 },
    FederalBracket { threshold: 1136211.0, rate: 0.168 },
    FederalBracket { threshold: 1431361.0, rate: 0.17600000000000002 },
    FederalBracket { threshold: 1847049.0, rate: 0.18 },
];

/// Simple-tax scale for canton LU, single taxpayer.
pub const LU_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 0.0, rate: 0.005 },
    FederalBracket { threshold: 9900.0, rate: 0.01 },
    FederalBracket { threshold: 22200.0, rate: 0.02 },
    FederalBracket { threshold: 37700.0, rate: 0.03 },
    FederalBracket { threshold: 54400.0, rate: 0.04 },
    FederalBracket { threshold: 72300.0, rate: 0.045 },
    FederalBracket { threshold: 93100.0, rate: 0.05 },
    FederalBracket { threshold: 118200.0, rate: 0.0525 },
    FederalBracket { threshold: 228300.0, rate: 0.055 },
    FederalBracket { threshold: 392200.0, rate: 0.057999999999999996 },
    FederalBracket { threshold: 582300.0, rate: 0.057 },
];

/// Simple-tax scale for canton LU, married taxpayer.
pub const LU_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 0.0, rate: 0.005 },
    FederalBracket { threshold: 19900.0, rate: 0.015 },
    FederalBracket { threshold: 43900.0, rate: 0.025 },
    FederalBracket { threshold: 68900.0, rate: 0.03 },
    FederalBracket { threshold: 95100.0, rate: 0.035 },
    FederalBracket { threshold: 123400.0, rate: 0.045 },
    FederalBracket { threshold: 155900.0, rate: 0.05 },
    FederalBracket { threshold: 255100.0, rate: 0.055 },
    FederalBracket { threshold: 393200.0, rate: 0.057999999999999996 },
    FederalBracket { threshold: 552400.0, rate: 0.055999999999999994 },
];

/// Simple-tax scale for canton SH, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const SH_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 0.0, rate: 0.01 },
    FederalBracket { threshold: 6300.0, rate: 0.02 },
    FederalBracket { threshold: 12900.0, rate: 0.03 },
    FederalBracket { threshold: 21200.0, rate: 0.04 },
    FederalBracket { threshold: 31600.0, rate: 0.05 },
    FederalBracket { threshold: 44300.0, rate: 0.06 },
    FederalBracket { threshold: 64900.0, rate: 0.07 },
    FederalBracket { threshold: 93400.0, rate: 0.08 },
    FederalBracket { threshold: 129800.0, rate: 0.09 },
    FederalBracket { threshold: 174100.0, rate: 0.1 },
    FederalBracket { threshold: 231000.0, rate: 0.11 },
    FederalBracket { threshold: 300500.0, rate: 0.12 },
    FederalBracket { threshold: 441500.0, rate: 0.099 },
    FederalBracket { threshold: 651600.0, rate: 0.099 },
];

/// Simple-tax scale for canton SH, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const SH_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 0.0, rate: 0.01 },
    FederalBracket { threshold: 6300.0, rate: 0.02 },
    FederalBracket { threshold: 12900.0, rate: 0.03 },
    FederalBracket { threshold: 21200.0, rate: 0.04 },
    FederalBracket { threshold: 31600.0, rate: 0.05 },
    FederalBracket { threshold: 44300.0, rate: 0.06 },
    FederalBracket { threshold: 64900.0, rate: 0.07 },
    FederalBracket { threshold: 93400.0, rate: 0.08 },
    FederalBracket { threshold: 129800.0, rate: 0.09 },
    FederalBracket { threshold: 174100.0, rate: 0.1 },
    FederalBracket { threshold: 231000.0, rate: 0.11 },
    FederalBracket { threshold: 300500.0, rate: 0.12 },
    FederalBracket { threshold: 441500.0, rate: 0.099 },
    FederalBracket { threshold: 651600.0, rate: 0.099 },
];

/// Simple-tax scale for canton SO, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const SO_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 0.0, rate: 0.045 },
    FederalBracket { threshold: 12400.0, rate: 0.05 },
    FederalBracket { threshold: 28900.0, rate: 0.065 },
    FederalBracket { threshold: 49500.0, rate: 0.08 },
    FederalBracket { threshold: 73200.0, rate: 0.09 },
    FederalBracket { threshold: 99000.0, rate: 0.095 },
    FederalBracket { threshold: 127900.0, rate: 0.1 },
    FederalBracket { threshold: 168100.0, rate: 0.105 },
    FederalBracket { threshold: 223800.0, rate: 0.115 },
    FederalBracket { threshold: 324900.0, rate: 0.105 },
];

/// Simple-tax scale for canton SO, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const SO_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 0.0, rate: 0.045 },
    FederalBracket { threshold: 12400.0, rate: 0.05 },
    FederalBracket { threshold: 28900.0, rate: 0.065 },
    FederalBracket { threshold: 49500.0, rate: 0.08 },
    FederalBracket { threshold: 73200.0, rate: 0.09 },
    FederalBracket { threshold: 99000.0, rate: 0.095 },
    FederalBracket { threshold: 127900.0, rate: 0.1 },
    FederalBracket { threshold: 168100.0, rate: 0.105 },
    FederalBracket { threshold: 223800.0, rate: 0.115 },
    FederalBracket { threshold: 324900.0, rate: 0.105 },
];

/// Simple-tax scale for canton ZH, single taxpayer.
pub const ZH_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 7000.0, rate: 0.02 },
    FederalBracket { threshold: 12000.0, rate: 0.03 },
    FederalBracket { threshold: 16800.0, rate: 0.04 },
    FederalBracket { threshold: 24800.0, rate: 0.05 },
    FederalBracket { threshold: 34500.0, rate: 0.06 },
    FederalBracket { threshold: 45700.0, rate: 0.07 },
    FederalBracket { threshold: 58800.0, rate: 0.08 },
    FederalBracket { threshold: 76400.0, rate: 0.09 },
    FederalBracket { threshold: 110400.0, rate: 0.1 },
    FederalBracket { threshold: 144100.0, rate: 0.11 },
    FederalBracket { threshold: 197400.0, rate: 0.12 },
    FederalBracket { threshold: 266700.0, rate: 0.13 },
];

/// Simple-tax scale for canton ZH, married taxpayer.
pub const ZH_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 14100.0, rate: 0.02 },
    FederalBracket { threshold: 20500.0, rate: 0.03 },
    FederalBracket { threshold: 28600.0, rate: 0.04 },
    FederalBracket { threshold: 38400.0, rate: 0.05 },
    FederalBracket { threshold: 49600.0, rate: 0.06 },
    FederalBracket { threshold: 64100.0, rate: 0.07 },
    FederalBracket { threshold: 96300.0, rate: 0.08 },
    FederalBracket { threshold: 128700.0, rate: 0.09 },
    FederalBracket { threshold: 177200.0, rate: 0.1 },
    FederalBracket { threshold: 235100.0, rate: 0.11 },
    FederalBracket { threshold: 298000.0, rate: 0.12 },
    FederalBracket { threshold: 370600.0, rate: 0.13 },
];

/// Every imported scale.
pub const BASE_SCALES: &[BaseScale] = &[
    BaseScale {
        canton_code: "AG",
        splitting_factor_married: Some(2.0),
        single: AG_SINGLE_BRACKETS,
        married: AG_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "BS",
        splitting_factor_married: None,
        single: BS_SINGLE_BRACKETS,
        married: BS_MARRIED_BRACKETS,
        shared_scale: false,
        subjects: &["Alleinstehend ohne Kinder", "Verheiratet / Alleinstehend mit Kindern"],
    },
    BaseScale {
        canton_code: "FR",
        splitting_factor_married: None,
        single: FR_SINGLE_BRACKETS,
        married: FR_MARRIED_BRACKETS,
        shared_scale: false,
        subjects: &["Alleinstehend ohne Kinder", "Verheiratet / Alleinstehend mit Kindern"],
    },
    BaseScale {
        canton_code: "GE",
        splitting_factor_married: Some(2.0),
        single: GE_SINGLE_BRACKETS,
        married: GE_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "LU",
        splitting_factor_married: None,
        single: LU_SINGLE_BRACKETS,
        married: LU_MARRIED_BRACKETS,
        shared_scale: false,
        subjects: &["Alleinstehend ohne Kinder", "Verheiratet / Alleinstehend mit Kindern"],
    },
    BaseScale {
        canton_code: "SH",
        splitting_factor_married: Some(1.9),
        single: SH_SINGLE_BRACKETS,
        married: SH_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "SO",
        splitting_factor_married: Some(1.9),
        single: SO_SINGLE_BRACKETS,
        married: SO_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "ZH",
        splitting_factor_married: None,
        single: ZH_SINGLE_BRACKETS,
        married: ZH_MARRIED_BRACKETS,
        shared_scale: false,
        subjects: &["Alleinstehend ohne Kinder", "Verheiratet / Alleinstehend mit Kindern"],
    },
];

/// Look up an imported scale by canton code.
pub fn base_scale(canton_code: &str) -> Option<&'static BaseScale> {
    BASE_SCALES.iter().find(|s| s.canton_code == canton_code)
}
