// Life Optimizer
// Copyright (C) 2026 MILAN NIKOLIC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! Cantonal simple-tax scales imported from ESTV "Tarife" exports.
//!
//! GENERATED by `tools/import_estv_scales.py` -- do not edit by hand;
//! re-run the importer instead.
//!
//! Source: ESTV tax calculator Tarife exports (23 files):
//!   * `estv_scales_AG.xlsx`
//!   * `estv_scales_AI.xlsx`
//!   * `estv_scales_AR.xlsx`
//!   * `estv_scales_BS.xlsx`
//!   * `estv_scales_Bund.xlsx`
//!   * `estv_scales_FR.xlsx`
//!   * `estv_scales_GE.xlsx`
//!   * `estv_scales_GL.xlsx`
//!   * `estv_scales_GR.xlsx`
//!   * `estv_scales_JU.xlsx`
//!   * `estv_scales_LU.xlsx`
//!   * `estv_scales_NE.xlsx`
//!   * `estv_scales_NW.xlsx`
//!   * `estv_scales_SG.xlsx`
//!   * `estv_scales_SH.xlsx`
//!   * `estv_scales_SO.xlsx`
//!   * `estv_scales_SZ.xlsx`
//!   * `estv_scales_TG.xlsx`
//!   * `estv_scales_TI.xlsx`
//!   * `estv_scales_VD.xlsx`
//!   * `estv_scales_VS.xlsx`
//!   * `estv_scales_ZG.xlsx`
//!   * `estv_scales_ZH.xlsx`
//!
//! `threshold` is the income level at which the band begins and `rate` is
//! that band's marginal rate as a fraction. The ESTV export expresses the
//! same schedule as band *widths* ("Für die nächsten CHF"); the importer
//! accumulates those widths into thresholds, which is an exact conversion
//! for the marginal structure.
//!
//! # Marital treatment is expressed in two different ways
//!
//! Cantons differ, and the two axes must not be applied together:
//!
//! * A canton publishing ONE scale (`Steuersubjekt = Alle`) expresses the
//!   marital difference through the **splitting factor**, which applies
//!   only to married taxpayers.
//! * A canton publishing SEPARATE scales per `Steuersubjekt` has already
//!   encoded the difference in the scale, so the splitting factor is
//!   `None` here and must not be applied on top.

use crate::federal_tax::FederalBracket;

/// One canton's imported simple-tax scale.
#[derive(Debug, Clone, Copy)]
pub struct BaseScale {
    pub canton_code: &'static str,
    /// Income-splitting divisor for MARRIED taxpayers, applied only when the
    /// canton publishes a single shared scale. `None` when marital status is
    /// already encoded in the separate `single`/`married` scales.
    pub splitting_factor_married: Option<f64>,
    /// Marginal bands for a single taxpayer.
    pub single: &'static [FederalBracket],
    /// Marginal bands for a married taxpayer.
    pub married: &'static [FederalBracket],
    /// True when the canton publishes one scale for all taxpayers.
    pub shared_scale: bool,
    /// The `Steuersubjekt` values present in the export, so an unexpected
    /// subject split is visible rather than silently merged.
    pub subjects: &'static [&'static str],
}

impl BaseScale {
    /// The bands that apply to the given marital status.
    pub fn brackets(&self, married: bool) -> &'static [FederalBracket] {
        if married { self.married } else { self.single }
    }

    /// The splitting factor to apply, which is only ever non-`None` for a
    /// married taxpayer on a shared scale.
    pub fn splitting_factor(&self, married: bool) -> Option<f64> {
        if married { self.splitting_factor_married } else { None }
    }
}

/// Simple-tax scale for canton AG, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const AG_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 4300.0, rate: 0.01 },
    FederalBracket { threshold: 8100.0, rate: 0.02 },
    FederalBracket { threshold: 12000.0, rate: 0.03 },
    FederalBracket { threshold: 16200.0, rate: 0.04 },
    FederalBracket { threshold: 20500.0, rate: 0.05 },
    FederalBracket { threshold: 25700.0, rate: 0.06 },
    FederalBracket { threshold: 33100.0, rate: 0.07 },
    FederalBracket { threshold: 41700.0, rate: 0.08 },
    FederalBracket { threshold: 51300.0, rate: 0.085 },
    FederalBracket { threshold: 63100.0, rate: 0.09 },
    FederalBracket { threshold: 74800.0, rate: 0.095 },
    FederalBracket { threshold: 110100.0, rate: 0.1 },
    FederalBracket { threshold: 176400.0, rate: 0.105 },
    FederalBracket { threshold: 352700.0, rate: 0.11 },
];

/// Simple-tax scale for canton AG, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const AG_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 4300.0, rate: 0.01 },
    FederalBracket { threshold: 8100.0, rate: 0.02 },
    FederalBracket { threshold: 12000.0, rate: 0.03 },
    FederalBracket { threshold: 16200.0, rate: 0.04 },
    FederalBracket { threshold: 20500.0, rate: 0.05 },
    FederalBracket { threshold: 25700.0, rate: 0.06 },
    FederalBracket { threshold: 33100.0, rate: 0.07 },
    FederalBracket { threshold: 41700.0, rate: 0.08 },
    FederalBracket { threshold: 51300.0, rate: 0.085 },
    FederalBracket { threshold: 63100.0, rate: 0.09 },
    FederalBracket { threshold: 74800.0, rate: 0.095 },
    FederalBracket { threshold: 110100.0, rate: 0.1 },
    FederalBracket { threshold: 176400.0, rate: 0.105 },
    FederalBracket { threshold: 352700.0, rate: 0.11 },
];

/// Simple-tax scale for canton AI, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const AI_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 3000.0, rate: 0.01 },
    FederalBracket { threshold: 6000.0, rate: 0.02 },
    FederalBracket { threshold: 9000.0, rate: 0.03 },
    FederalBracket { threshold: 12000.0, rate: 0.04 },
    FederalBracket { threshold: 15000.0, rate: 0.05 },
    FederalBracket { threshold: 18000.0, rate: 0.06 },
    FederalBracket { threshold: 22000.0, rate: 0.07 },
    FederalBracket { threshold: 26000.0, rate: 0.075 },
    FederalBracket { threshold: 30000.0, rate: 0.08 },
    FederalBracket { threshold: 40000.0, rate: 0.085 },
    FederalBracket { threshold: 74000.0, rate: 0.09 },
    FederalBracket { threshold: 140000.0, rate: 0.085 },
    FederalBracket { threshold: 200000.0, rate: 0.08 },
];

/// Simple-tax scale for canton AI, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const AI_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 3000.0, rate: 0.01 },
    FederalBracket { threshold: 6000.0, rate: 0.02 },
    FederalBracket { threshold: 9000.0, rate: 0.03 },
    FederalBracket { threshold: 12000.0, rate: 0.04 },
    FederalBracket { threshold: 15000.0, rate: 0.05 },
    FederalBracket { threshold: 18000.0, rate: 0.06 },
    FederalBracket { threshold: 22000.0, rate: 0.07 },
    FederalBracket { threshold: 26000.0, rate: 0.075 },
    FederalBracket { threshold: 30000.0, rate: 0.08 },
    FederalBracket { threshold: 40000.0, rate: 0.085 },
    FederalBracket { threshold: 74000.0, rate: 0.09 },
    FederalBracket { threshold: 140000.0, rate: 0.085 },
    FederalBracket { threshold: 200000.0, rate: 0.08 },
];

/// Simple-tax scale for canton AR, single taxpayer.
pub const AR_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 8300.0, rate: 0.006 },
    FederalBracket { threshold: 9900.0, rate: 0.01 },
    FederalBracket { threshold: 11500.0, rate: 0.015 },
    FederalBracket { threshold: 15700.0, rate: 0.018000000000000002 },
    FederalBracket { threshold: 27200.0, rate: 0.022000000000000002 },
    FederalBracket { threshold: 41800.0, rate: 0.024 },
    FederalBracket { threshold: 54300.0, rate: 0.026000000000000002 },
    FederalBracket { threshold: 74100.0, rate: 0.027000000000000003 },
    FederalBracket { threshold: 88700.0, rate: 0.027999999999999997 },
    FederalBracket { threshold: 125200.0, rate: 0.028999999999999998 },
    FederalBracket { threshold: 260800.0, rate: 0.026000000000000002 },
];

/// Simple-tax scale for canton AR, married taxpayer.
pub const AR_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 16700.0, rate: 0.005 },
    FederalBracket { threshold: 18800.0, rate: 0.009000000000000001 },
    FederalBracket { threshold: 21900.0, rate: 0.013999999999999999 },
    FederalBracket { threshold: 27100.0, rate: 0.017 },
    FederalBracket { threshold: 36500.0, rate: 0.019 },
    FederalBracket { threshold: 52100.0, rate: 0.022000000000000002 },
    FederalBracket { threshold: 67700.0, rate: 0.025 },
    FederalBracket { threshold: 88600.0, rate: 0.027000000000000003 },
    FederalBracket { threshold: 114700.0, rate: 0.027999999999999997 },
    FederalBracket { threshold: 177300.0, rate: 0.028999999999999998 },
    FederalBracket { threshold: 417200.0, rate: 0.026000000000000002 },
];

/// Simple-tax scale for canton BS, single taxpayer.
pub const BS_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.21 },
    FederalBracket { threshold: 212500.0, rate: 0.2725 },
    FederalBracket { threshold: 316300.0, rate: 0.2825 },
];

/// Simple-tax scale for canton BS, married taxpayer.
pub const BS_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.21 },
    FederalBracket { threshold: 424900.0, rate: 0.2725 },
    FederalBracket { threshold: 632500.0, rate: 0.2825 },
];

/// Simple-tax scale for canton Bund, single taxpayer.
pub const BUND_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 15200.0, rate: 0.0077 },
    FederalBracket { threshold: 33200.0, rate: 0.0088 },
    FederalBracket { threshold: 43500.0, rate: 0.0264 },
    FederalBracket { threshold: 58000.0, rate: 0.029699999999999997 },
    FederalBracket { threshold: 76100.0, rate: 0.059399999999999994 },
    FederalBracket { threshold: 82000.0, rate: 0.066 },
    FederalBracket { threshold: 108800.0, rate: 0.08800000000000001 },
    FederalBracket { threshold: 141500.0, rate: 0.11 },
    FederalBracket { threshold: 184900.0, rate: 0.132 },
    FederalBracket { threshold: 793300.0, rate: 0.132 },
    FederalBracket { threshold: 793400.0, rate: 0.115 },
];

/// Simple-tax scale for canton Bund, married taxpayer.
pub const BUND_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 29700.0, rate: 0.01 },
    FederalBracket { threshold: 53400.0, rate: 0.02 },
    FederalBracket { threshold: 61300.0, rate: 0.03 },
    FederalBracket { threshold: 79100.0, rate: 0.04 },
    FederalBracket { threshold: 94900.0, rate: 0.05 },
    FederalBracket { threshold: 108600.0, rate: 0.06 },
    FederalBracket { threshold: 120500.0, rate: 0.07 },
    FederalBracket { threshold: 130500.0, rate: 0.08 },
    FederalBracket { threshold: 138300.0, rate: 0.09 },
    FederalBracket { threshold: 144200.0, rate: 0.1 },
    FederalBracket { threshold: 148200.0, rate: 0.11 },
    FederalBracket { threshold: 150300.0, rate: 0.12 },
    FederalBracket { threshold: 152300.0, rate: 0.13 },
    FederalBracket { threshold: 940800.0, rate: 0.13 },
    FederalBracket { threshold: 940900.0, rate: 0.115 },
];

/// Simple-tax scale for canton FR, single taxpayer.
pub const FR_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 5199.0, rate: 0.0 },
    FederalBracket { threshold: 5200.0, rate: 0.01 },
    FederalBracket { threshold: 17500.0, rate: 0.041745000000000004 },
    FederalBracket { threshold: 31400.0, rate: 0.062139 },
    FederalBracket { threshold: 48300.0, rate: 0.08035199999999999 },
    FederalBracket { threshold: 63800.0, rate: 0.09104200000000001 },
    FederalBracket { threshold: 77600.0, rate: 0.099846 },
    FederalBracket { threshold: 102100.0, rate: 0.108662 },
    FederalBracket { threshold: 128700.0, rate: 0.117172 },
    FederalBracket { threshold: 156000.0, rate: 0.125355 },
    FederalBracket { threshold: 181000.0, rate: 0.131097 },
    FederalBracket { threshold: 207100.0, rate: 0.135 },
];

/// Simple-tax scale for canton FR, married taxpayer.
pub const FR_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 5199.0, rate: 0.0 },
    FederalBracket { threshold: 5200.0, rate: 0.01 },
    FederalBracket { threshold: 10500.0, rate: 0.01 },
    FederalBracket { threshold: 35000.0, rate: 0.041745000000000004 },
    FederalBracket { threshold: 62800.0, rate: 0.062139 },
    FederalBracket { threshold: 96600.0, rate: 0.08035199999999999 },
    FederalBracket { threshold: 127600.0, rate: 0.09104200000000001 },
    FederalBracket { threshold: 155200.0, rate: 0.099846 },
    FederalBracket { threshold: 204200.0, rate: 0.108662 },
    FederalBracket { threshold: 257400.0, rate: 0.117172 },
    FederalBracket { threshold: 312000.0, rate: 0.125355 },
    FederalBracket { threshold: 362000.0, rate: 0.131097 },
    FederalBracket { threshold: 414200.0, rate: 0.135 },
];

/// Simple-tax scale for canton GE, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const GE_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 18700.0, rate: 0.073 },
    FederalBracket { threshold: 22530.0, rate: 0.08199999999999999 },
    FederalBracket { threshold: 24784.0, rate: 0.091 },
    FederalBracket { threshold: 27036.0, rate: 0.1 },
    FederalBracket { threshold: 29290.0, rate: 0.109 },
    FederalBracket { threshold: 34922.0, rate: 0.113 },
    FederalBracket { threshold: 39428.0, rate: 0.12300000000000001 },
    FederalBracket { threshold: 43935.0, rate: 0.128 },
    FederalBracket { threshold: 48441.0, rate: 0.132 },
    FederalBracket { threshold: 77730.0, rate: 0.142 },
    FederalBracket { threshold: 127297.0, rate: 0.15 },
    FederalBracket { threshold: 171231.0, rate: 0.156 },
    FederalBracket { threshold: 193762.0, rate: 0.158 },
    FederalBracket { threshold: 277125.0, rate: 0.16 },
    FederalBracket { threshold: 295150.0, rate: 0.168 },
    FederalBracket { threshold: 415688.0, rate: 0.17600000000000002 },
    FederalBracket { threshold: 651131.0, rate: 0.18 },
];

/// Simple-tax scale for canton GE, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const GE_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 18700.0, rate: 0.073 },
    FederalBracket { threshold: 22530.0, rate: 0.08199999999999999 },
    FederalBracket { threshold: 24784.0, rate: 0.091 },
    FederalBracket { threshold: 27036.0, rate: 0.1 },
    FederalBracket { threshold: 29290.0, rate: 0.109 },
    FederalBracket { threshold: 34922.0, rate: 0.113 },
    FederalBracket { threshold: 39428.0, rate: 0.12300000000000001 },
    FederalBracket { threshold: 43935.0, rate: 0.128 },
    FederalBracket { threshold: 48441.0, rate: 0.132 },
    FederalBracket { threshold: 77730.0, rate: 0.142 },
    FederalBracket { threshold: 127297.0, rate: 0.15 },
    FederalBracket { threshold: 171231.0, rate: 0.156 },
    FederalBracket { threshold: 193762.0, rate: 0.158 },
    FederalBracket { threshold: 277125.0, rate: 0.16 },
    FederalBracket { threshold: 295150.0, rate: 0.168 },
    FederalBracket { threshold: 415688.0, rate: 0.17600000000000002 },
    FederalBracket { threshold: 651131.0, rate: 0.18 },
];

/// Simple-tax scale for canton GL, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const GL_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 10300.0, rate: 0.08 },
    FederalBracket { threshold: 20600.0, rate: 0.11 },
    FederalBracket { threshold: 30900.0, rate: 0.13 },
    FederalBracket { threshold: 51600.0, rate: 0.15 },
    FederalBracket { threshold: 103200.0, rate: 0.16 },
    FederalBracket { threshold: 154700.0, rate: 0.175 },
    FederalBracket { threshold: 257900.0, rate: 0.19 },
    FederalBracket { threshold: 412600.0, rate: 0.21 },
    FederalBracket { threshold: 464200.0, rate: 0.17 },
];

/// Simple-tax scale for canton GL, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const GL_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 10300.0, rate: 0.08 },
    FederalBracket { threshold: 20600.0, rate: 0.11 },
    FederalBracket { threshold: 30900.0, rate: 0.13 },
    FederalBracket { threshold: 51600.0, rate: 0.15 },
    FederalBracket { threshold: 103200.0, rate: 0.16 },
    FederalBracket { threshold: 154700.0, rate: 0.175 },
    FederalBracket { threshold: 257900.0, rate: 0.19 },
    FederalBracket { threshold: 412600.0, rate: 0.21 },
    FederalBracket { threshold: 464200.0, rate: 0.17 },
];

/// Simple-tax scale for canton GR, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const GR_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 16895.0, rate: 0.025 },
    FederalBracket { threshold: 17985.0, rate: 0.04 },
    FederalBracket { threshold: 19075.0, rate: 0.05 },
    FederalBracket { threshold: 20165.0, rate: 0.06 },
    FederalBracket { threshold: 21255.0, rate: 0.065 },
    FederalBracket { threshold: 22345.0, rate: 0.07 },
    FederalBracket { threshold: 24525.0, rate: 0.08 },
    FederalBracket { threshold: 31065.0, rate: 0.085 },
    FederalBracket { threshold: 35425.0, rate: 0.09 },
    FederalBracket { threshold: 39785.0, rate: 0.095 },
    FederalBracket { threshold: 44145.0, rate: 0.10300000000000001 },
    FederalBracket { threshold: 65945.0, rate: 0.106 },
    FederalBracket { threshold: 87745.0, rate: 0.107 },
    FederalBracket { threshold: 109545.0, rate: 0.11199999999999999 },
    FederalBracket { threshold: 218545.0, rate: 0.113 },
    FederalBracket { threshold: 327545.0, rate: 0.114 },
    FederalBracket { threshold: 436545.0, rate: 0.11599999999999999 },
    FederalBracket { threshold: 780440.0, rate: 0.11 },
    FederalBracket { threshold: 780441.0, rate: 0.11 },
];

/// Simple-tax scale for canton GR, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const GR_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 16895.0, rate: 0.025 },
    FederalBracket { threshold: 17985.0, rate: 0.04 },
    FederalBracket { threshold: 19075.0, rate: 0.05 },
    FederalBracket { threshold: 20165.0, rate: 0.06 },
    FederalBracket { threshold: 21255.0, rate: 0.065 },
    FederalBracket { threshold: 22345.0, rate: 0.07 },
    FederalBracket { threshold: 24525.0, rate: 0.08 },
    FederalBracket { threshold: 31065.0, rate: 0.085 },
    FederalBracket { threshold: 35425.0, rate: 0.09 },
    FederalBracket { threshold: 39785.0, rate: 0.095 },
    FederalBracket { threshold: 44145.0, rate: 0.10300000000000001 },
    FederalBracket { threshold: 65945.0, rate: 0.106 },
    FederalBracket { threshold: 87745.0, rate: 0.107 },
    FederalBracket { threshold: 109545.0, rate: 0.11199999999999999 },
    FederalBracket { threshold: 218545.0, rate: 0.113 },
    FederalBracket { threshold: 327545.0, rate: 0.114 },
    FederalBracket { threshold: 436545.0, rate: 0.11599999999999999 },
    FederalBracket { threshold: 780440.0, rate: 0.11 },
    FederalBracket { threshold: 780441.0, rate: 0.11 },
];

/// Simple-tax scale for canton JU, single taxpayer.
pub const JU_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 6900.0, rate: 0.0166702 },
    FederalBracket { threshold: 14700.0, rate: 0.0314902 },
    FederalBracket { threshold: 28700.0, rate: 0.0402902 },
    FederalBracket { threshold: 50500.0, rate: 0.0490902 },
    FederalBracket { threshold: 92700.0, rate: 0.05558 },
    FederalBracket { threshold: 205200.0, rate: 0.057890199999999996 },
];

/// Simple-tax scale for canton JU, married taxpayer.
pub const JU_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 12600.0, rate: 0.0088 },
    FederalBracket { threshold: 18800.0, rate: 0.022690199999999997 },
    FederalBracket { threshold: 28100.0, rate: 0.03242 },
    FederalBracket { threshold: 48400.0, rate: 0.04122 },
    FederalBracket { threshold: 90600.0, rate: 0.0477102 },
    FederalBracket { threshold: 203100.0, rate: 0.0569702 },
    FederalBracket { threshold: 437600.0, rate: 0.057890199999999996 },
];

/// Simple-tax scale for canton LU, single taxpayer.
pub const LU_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 9900.0, rate: 0.005 },
    FederalBracket { threshold: 12300.0, rate: 0.01 },
    FederalBracket { threshold: 15500.0, rate: 0.02 },
    FederalBracket { threshold: 16700.0, rate: 0.03 },
    FederalBracket { threshold: 17900.0, rate: 0.04 },
    FederalBracket { threshold: 20800.0, rate: 0.045 },
    FederalBracket { threshold: 25100.0, rate: 0.05 },
    FederalBracket { threshold: 110100.0, rate: 0.0525 },
    FederalBracket { threshold: 163900.0, rate: 0.055 },
    FederalBracket { threshold: 190100.0, rate: 0.057999999999999996 },
    FederalBracket { threshold: 2096800.0, rate: 0.057 },
];

/// Simple-tax scale for canton LU, married taxpayer.
pub const LU_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 19900.0, rate: 0.005 },
    FederalBracket { threshold: 24000.0, rate: 0.015 },
    FederalBracket { threshold: 25000.0, rate: 0.025 },
    FederalBracket { threshold: 26200.0, rate: 0.03 },
    FederalBracket { threshold: 28300.0, rate: 0.035 },
    FederalBracket { threshold: 32500.0, rate: 0.045 },
    FederalBracket { threshold: 99200.0, rate: 0.05 },
    FederalBracket { threshold: 138100.0, rate: 0.055 },
    FederalBracket { threshold: 159200.0, rate: 0.057999999999999996 },
    FederalBracket { threshold: 1425500.0, rate: 0.055999999999999994 },
];

/// Simple-tax scale for canton NE, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const NE_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 7700.0, rate: 0.019799999999999998 },
    FederalBracket { threshold: 10300.0, rate: 0.039599999999999996 },
    FederalBracket { threshold: 15500.0, rate: 0.07919999999999999 },
    FederalBracket { threshold: 20600.0, rate: 0.11484 },
    FederalBracket { threshold: 30900.0, rate: 0.11781000000000001 },
    FederalBracket { threshold: 41200.0, rate: 0.12176999999999999 },
    FederalBracket { threshold: 51500.0, rate: 0.12672 },
    FederalBracket { threshold: 61800.0, rate: 0.13167 },
    FederalBracket { threshold: 72100.0, rate: 0.13662000000000002 },
    FederalBracket { threshold: 82400.0, rate: 0.14058 },
    FederalBracket { threshold: 92700.0, rate: 0.14355 },
    FederalBracket { threshold: 103000.0, rate: 0.14651999999999998 },
    FederalBracket { threshold: 113300.0, rate: 0.14949 },
    FederalBracket { threshold: 123600.0, rate: 0.15246 },
    FederalBracket { threshold: 133900.0, rate: 0.15345 },
    FederalBracket { threshold: 144200.0, rate: 0.15444000000000002 },
    FederalBracket { threshold: 154500.0, rate: 0.15542999999999998 },
    FederalBracket { threshold: 164800.0, rate: 0.15741 },
    FederalBracket { threshold: 175100.0, rate: 0.15939 },
    FederalBracket { threshold: 185400.0, rate: 0.16038 },
    FederalBracket { threshold: 195700.0, rate: 0.16038 },
    FederalBracket { threshold: 206000.0, rate: 0.13365 },
    FederalBracket { threshold: 309000.0, rate: 0.136125 },
    FederalBracket { threshold: 412000.0, rate: 0.1386 },
];

/// Simple-tax scale for canton NE, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const NE_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 7700.0, rate: 0.019799999999999998 },
    FederalBracket { threshold: 10300.0, rate: 0.039599999999999996 },
    FederalBracket { threshold: 15500.0, rate: 0.07919999999999999 },
    FederalBracket { threshold: 20600.0, rate: 0.11484 },
    FederalBracket { threshold: 30900.0, rate: 0.11781000000000001 },
    FederalBracket { threshold: 41200.0, rate: 0.12176999999999999 },
    FederalBracket { threshold: 51500.0, rate: 0.12672 },
    FederalBracket { threshold: 61800.0, rate: 0.13167 },
    FederalBracket { threshold: 72100.0, rate: 0.13662000000000002 },
    FederalBracket { threshold: 82400.0, rate: 0.14058 },
    FederalBracket { threshold: 92700.0, rate: 0.14355 },
    FederalBracket { threshold: 103000.0, rate: 0.14651999999999998 },
    FederalBracket { threshold: 113300.0, rate: 0.14949 },
    FederalBracket { threshold: 123600.0, rate: 0.15246 },
    FederalBracket { threshold: 133900.0, rate: 0.15345 },
    FederalBracket { threshold: 144200.0, rate: 0.15444000000000002 },
    FederalBracket { threshold: 154500.0, rate: 0.15542999999999998 },
    FederalBracket { threshold: 164800.0, rate: 0.15741 },
    FederalBracket { threshold: 175100.0, rate: 0.15939 },
    FederalBracket { threshold: 185400.0, rate: 0.16038 },
    FederalBracket { threshold: 195700.0, rate: 0.16038 },
    FederalBracket { threshold: 206000.0, rate: 0.13365 },
    FederalBracket { threshold: 309000.0, rate: 0.136125 },
    FederalBracket { threshold: 412000.0, rate: 0.1386 },
];

/// Simple-tax scale for canton NW, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const NW_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 11600.0, rate: 0.005 },
    FederalBracket { threshold: 14000.0, rate: 0.01 },
    FederalBracket { threshold: 15200.0, rate: 0.012 },
    FederalBracket { threshold: 16400.0, rate: 0.013999999999999999 },
    FederalBracket { threshold: 17600.0, rate: 0.016 },
    FederalBracket { threshold: 18800.0, rate: 0.018000000000000002 },
    FederalBracket { threshold: 20000.0, rate: 0.02 },
    FederalBracket { threshold: 21200.0, rate: 0.022000000000000002 },
    FederalBracket { threshold: 22400.0, rate: 0.024 },
    FederalBracket { threshold: 23600.0, rate: 0.026000000000000002 },
    FederalBracket { threshold: 24800.0, rate: 0.027999999999999997 },
    FederalBracket { threshold: 32800.0, rate: 0.028999999999999998 },
    FederalBracket { threshold: 50100.0, rate: 0.03 },
    FederalBracket { threshold: 81300.0, rate: 0.031 },
    FederalBracket { threshold: 116000.0, rate: 0.032 },
    FederalBracket { threshold: 148800.0, rate: 0.033 },
    FederalBracket { threshold: 166000.0, rate: 0.0275 },
];

/// Simple-tax scale for canton NW, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const NW_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 11600.0, rate: 0.005 },
    FederalBracket { threshold: 14000.0, rate: 0.01 },
    FederalBracket { threshold: 15200.0, rate: 0.012 },
    FederalBracket { threshold: 16400.0, rate: 0.013999999999999999 },
    FederalBracket { threshold: 17600.0, rate: 0.016 },
    FederalBracket { threshold: 18800.0, rate: 0.018000000000000002 },
    FederalBracket { threshold: 20000.0, rate: 0.02 },
    FederalBracket { threshold: 21200.0, rate: 0.022000000000000002 },
    FederalBracket { threshold: 22400.0, rate: 0.024 },
    FederalBracket { threshold: 23600.0, rate: 0.026000000000000002 },
    FederalBracket { threshold: 24800.0, rate: 0.027999999999999997 },
    FederalBracket { threshold: 32800.0, rate: 0.028999999999999998 },
    FederalBracket { threshold: 50100.0, rate: 0.03 },
    FederalBracket { threshold: 81300.0, rate: 0.031 },
    FederalBracket { threshold: 116000.0, rate: 0.032 },
    FederalBracket { threshold: 148800.0, rate: 0.033 },
    FederalBracket { threshold: 166000.0, rate: 0.0275 },
];

/// Simple-tax scale for canton SG, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const SG_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 11600.0, rate: 0.04 },
    FederalBracket { threshold: 15800.0, rate: 0.06 },
    FederalBracket { threshold: 33800.0, rate: 0.08 },
    FederalBracket { threshold: 60200.0, rate: 0.092 },
    FederalBracket { threshold: 98300.0, rate: 0.094 },
    FederalBracket { threshold: 264200.0, rate: 0.085 },
];

/// Simple-tax scale for canton SG, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const SG_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 11600.0, rate: 0.04 },
    FederalBracket { threshold: 15800.0, rate: 0.06 },
    FederalBracket { threshold: 33800.0, rate: 0.08 },
    FederalBracket { threshold: 60200.0, rate: 0.092 },
    FederalBracket { threshold: 98300.0, rate: 0.094 },
    FederalBracket { threshold: 264200.0, rate: 0.085 },
];

/// Simple-tax scale for canton SH, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const SH_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 6300.0, rate: 0.01 },
    FederalBracket { threshold: 6600.0, rate: 0.02 },
    FederalBracket { threshold: 8300.0, rate: 0.03 },
    FederalBracket { threshold: 10400.0, rate: 0.04 },
    FederalBracket { threshold: 12700.0, rate: 0.05 },
    FederalBracket { threshold: 20600.0, rate: 0.06 },
    FederalBracket { threshold: 28500.0, rate: 0.07 },
    FederalBracket { threshold: 36400.0, rate: 0.08 },
    FederalBracket { threshold: 44300.0, rate: 0.09 },
    FederalBracket { threshold: 56900.0, rate: 0.1 },
    FederalBracket { threshold: 69500.0, rate: 0.11 },
    FederalBracket { threshold: 141000.0, rate: 0.12 },
    FederalBracket { threshold: 210100.0, rate: 0.099 },
    FederalBracket { threshold: 210200.0, rate: 0.099 },
];

/// Simple-tax scale for canton SH, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const SH_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 6300.0, rate: 0.01 },
    FederalBracket { threshold: 6600.0, rate: 0.02 },
    FederalBracket { threshold: 8300.0, rate: 0.03 },
    FederalBracket { threshold: 10400.0, rate: 0.04 },
    FederalBracket { threshold: 12700.0, rate: 0.05 },
    FederalBracket { threshold: 20600.0, rate: 0.06 },
    FederalBracket { threshold: 28500.0, rate: 0.07 },
    FederalBracket { threshold: 36400.0, rate: 0.08 },
    FederalBracket { threshold: 44300.0, rate: 0.09 },
    FederalBracket { threshold: 56900.0, rate: 0.1 },
    FederalBracket { threshold: 69500.0, rate: 0.11 },
    FederalBracket { threshold: 141000.0, rate: 0.12 },
    FederalBracket { threshold: 210100.0, rate: 0.099 },
    FederalBracket { threshold: 210200.0, rate: 0.099 },
];

/// Simple-tax scale for canton SO, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const SO_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 12400.0, rate: 0.045 },
    FederalBracket { threshold: 16500.0, rate: 0.05 },
    FederalBracket { threshold: 20600.0, rate: 0.065 },
    FederalBracket { threshold: 23700.0, rate: 0.08 },
    FederalBracket { threshold: 25800.0, rate: 0.09 },
    FederalBracket { threshold: 28900.0, rate: 0.095 },
    FederalBracket { threshold: 40200.0, rate: 0.1 },
    FederalBracket { threshold: 55700.0, rate: 0.105 },
    FederalBracket { threshold: 101100.0, rate: 0.115 },
    FederalBracket { threshold: 319900.0, rate: 0.105 },
];

/// Simple-tax scale for canton SO, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const SO_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 12400.0, rate: 0.045 },
    FederalBracket { threshold: 16500.0, rate: 0.05 },
    FederalBracket { threshold: 20600.0, rate: 0.065 },
    FederalBracket { threshold: 23700.0, rate: 0.08 },
    FederalBracket { threshold: 25800.0, rate: 0.09 },
    FederalBracket { threshold: 28900.0, rate: 0.095 },
    FederalBracket { threshold: 40200.0, rate: 0.1 },
    FederalBracket { threshold: 55700.0, rate: 0.105 },
    FederalBracket { threshold: 101100.0, rate: 0.115 },
    FederalBracket { threshold: 319900.0, rate: 0.105 },
];

/// Simple-tax scale for canton SZ, single taxpayer.
pub const SZ_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0025 },
    FederalBracket { threshold: 1500.0, rate: 0.005 },
    FederalBracket { threshold: 2800.0, rate: 0.0075 },
    FederalBracket { threshold: 3900.0, rate: 0.01 },
    FederalBracket { threshold: 4900.0, rate: 0.0125 },
    FederalBracket { threshold: 5900.0, rate: 0.015 },
    FederalBracket { threshold: 7000.0, rate: 0.0175 },
    FederalBracket { threshold: 8300.0, rate: 0.02 },
    FederalBracket { threshold: 10100.0, rate: 0.0225 },
    FederalBracket { threshold: 12500.0, rate: 0.025 },
    FederalBracket { threshold: 16100.0, rate: 0.0275 },
    FederalBracket { threshold: 22000.0, rate: 0.03 },
    FederalBracket { threshold: 30200.0, rate: 0.0325 },
    FederalBracket { threshold: 40700.0, rate: 0.035 },
    FederalBracket { threshold: 52300.0, rate: 0.0365 },
    FederalBracket { threshold: 61600.0, rate: 0.039 },
    FederalBracket { threshold: 258800.0, rate: 0.07 },
    FederalBracket { threshold: 433500.0, rate: 0.05 },
];

/// Simple-tax scale for canton SZ, married taxpayer.
pub const SZ_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0025 },
    FederalBracket { threshold: 1500.0, rate: 0.005 },
    FederalBracket { threshold: 2800.0, rate: 0.0075 },
    FederalBracket { threshold: 3900.0, rate: 0.01 },
    FederalBracket { threshold: 4900.0, rate: 0.0125 },
    FederalBracket { threshold: 5900.0, rate: 0.015 },
    FederalBracket { threshold: 7000.0, rate: 0.0175 },
    FederalBracket { threshold: 8300.0, rate: 0.02 },
    FederalBracket { threshold: 10100.0, rate: 0.0225 },
    FederalBracket { threshold: 12500.0, rate: 0.025 },
    FederalBracket { threshold: 16100.0, rate: 0.0275 },
    FederalBracket { threshold: 22000.0, rate: 0.03 },
    FederalBracket { threshold: 30200.0, rate: 0.0325 },
    FederalBracket { threshold: 40700.0, rate: 0.035 },
    FederalBracket { threshold: 52300.0, rate: 0.0365 },
    FederalBracket { threshold: 61600.0, rate: 0.039 },
    FederalBracket { threshold: 258800.0, rate: 0.07 },
    FederalBracket { threshold: 433500.0, rate: 0.05 },
];

/// Simple-tax scale for canton TG, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const TG_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 12200.0, rate: 0.02 },
    FederalBracket { threshold: 14600.0, rate: 0.03 },
    FederalBracket { threshold: 16800.0, rate: 0.04 },
    FederalBracket { threshold: 18900.0, rate: 0.05 },
    FederalBracket { threshold: 21000.0, rate: 0.06 },
    FederalBracket { threshold: 36800.0, rate: 0.07 },
    FederalBracket { threshold: 84400.0, rate: 0.075 },
    FederalBracket { threshold: 158400.0, rate: 0.08 },
];

/// Simple-tax scale for canton TG, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const TG_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 12200.0, rate: 0.02 },
    FederalBracket { threshold: 14600.0, rate: 0.03 },
    FederalBracket { threshold: 16800.0, rate: 0.04 },
    FederalBracket { threshold: 18900.0, rate: 0.05 },
    FederalBracket { threshold: 21000.0, rate: 0.06 },
    FederalBracket { threshold: 36800.0, rate: 0.07 },
    FederalBracket { threshold: 84400.0, rate: 0.075 },
    FederalBracket { threshold: 158400.0, rate: 0.08 },
];

/// Simple-tax scale for canton TI, single taxpayer.
pub const TI_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 12500.0, rate: 0.0016 },
    FederalBracket { threshold: 12600.0, rate: 0.052320000000000005 },
    FederalBracket { threshold: 17500.0, rate: 0.05949 },
    FederalBracket { threshold: 20900.0, rate: 0.03923 },
    FederalBracket { threshold: 26100.0, rate: 0.07499 },
    FederalBracket { threshold: 30200.0, rate: 0.09461 },
    FederalBracket { threshold: 40000.0, rate: 0.10377 },
    FederalBracket { threshold: 52800.0, rate: 0.10987999999999999 },
    FederalBracket { threshold: 58800.0, rate: 0.11800000000000001 },
    FederalBracket { threshold: 73100.0, rate: 0.11596999999999999 },
    FederalBracket { threshold: 91500.0, rate: 0.1247 },
    FederalBracket { threshold: 114000.0, rate: 0.1308 },
    FederalBracket { threshold: 227900.0, rate: 0.1404 },
    FederalBracket { threshold: 380700.0, rate: 0.14 },
];

/// Simple-tax scale for canton TI, married taxpayer.
pub const TI_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 20400.0, rate: 0.00145 },
    FederalBracket { threshold: 20500.0, rate: 0.03923 },
    FederalBracket { threshold: 24900.0, rate: 0.0436 },
    FederalBracket { threshold: 28300.0, rate: 0.026160000000000003 },
    FederalBracket { threshold: 33200.0, rate: 0.03923 },
    FederalBracket { threshold: 42400.0, rate: 0.0654 },
    FederalBracket { threshold: 47900.0, rate: 0.07848 },
    FederalBracket { threshold: 60700.0, rate: 0.10116 },
    FederalBracket { threshold: 79900.0, rate: 0.11074 },
    FederalBracket { threshold: 90500.0, rate: 0.12645 },
    FederalBracket { threshold: 122700.0, rate: 0.12034 },
    FederalBracket { threshold: 141100.0, rate: 0.12906 },
    FederalBracket { threshold: 183300.0, rate: 0.13777 },
    FederalBracket { threshold: 227900.0, rate: 0.14302 },
    FederalBracket { threshold: 304000.0, rate: 0.1465 },
    FederalBracket { threshold: 761500.0, rate: 0.14 },
];

/// Simple-tax scale for canton VD, single taxpayer.
pub const VD_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 100.0, rate: 0.01 },
    FederalBracket { threshold: 1600.0, rate: 0.02 },
    FederalBracket { threshold: 3400.0, rate: 0.03 },
    FederalBracket { threshold: 5100.0, rate: 0.04 },
    FederalBracket { threshold: 8300.0, rate: 0.05 },
    FederalBracket { threshold: 11900.0, rate: 0.06 },
    FederalBracket { threshold: 15100.0, rate: 0.07 },
    FederalBracket { threshold: 23600.0, rate: 0.08 },
    FederalBracket { threshold: 40500.0, rate: 0.09 },
    FederalBracket { threshold: 57200.0, rate: 0.1 },
    FederalBracket { threshold: 74400.0, rate: 0.11 },
    FederalBracket { threshold: 91200.0, rate: 0.12 },
    FederalBracket { threshold: 108100.0, rate: 0.125 },
    FederalBracket { threshold: 135000.0, rate: 0.13 },
    FederalBracket { threshold: 162000.0, rate: 0.135 },
    FederalBracket { threshold: 192500.0, rate: 0.14 },
    FederalBracket { threshold: 223000.0, rate: 0.145 },
    FederalBracket { threshold: 256000.0, rate: 0.15 },
    FederalBracket { threshold: 291700.0, rate: 0.155 },
];

/// Simple-tax scale for canton VD, married taxpayer.
pub const VD_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 100.0, rate: 0.01 },
    FederalBracket { threshold: 1600.0, rate: 0.02 },
    FederalBracket { threshold: 3400.0, rate: 0.03 },
    FederalBracket { threshold: 5100.0, rate: 0.04 },
    FederalBracket { threshold: 8300.0, rate: 0.05 },
    FederalBracket { threshold: 11900.0, rate: 0.06 },
    FederalBracket { threshold: 15100.0, rate: 0.07 },
    FederalBracket { threshold: 23600.0, rate: 0.08 },
    FederalBracket { threshold: 40500.0, rate: 0.09 },
    FederalBracket { threshold: 57200.0, rate: 0.1 },
    FederalBracket { threshold: 74400.0, rate: 0.11 },
    FederalBracket { threshold: 91200.0, rate: 0.12 },
    FederalBracket { threshold: 108100.0, rate: 0.125 },
    FederalBracket { threshold: 135000.0, rate: 0.13 },
    FederalBracket { threshold: 162000.0, rate: 0.135 },
    FederalBracket { threshold: 192500.0, rate: 0.14 },
    FederalBracket { threshold: 223000.0, rate: 0.145 },
    FederalBracket { threshold: 256000.0, rate: 0.15 },
    FederalBracket { threshold: 291700.0, rate: 0.155 },
];

/// Simple-tax scale for canton VS, single taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const VS_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.02 },
    FederalBracket { threshold: 5000.0, rate: 0.02 },
    FederalBracket { threshold: 10000.0, rate: 0.027999999999999997 },
    FederalBracket { threshold: 20000.0, rate: 0.046 },
    FederalBracket { threshold: 30000.0, rate: 0.06 },
    FederalBracket { threshold: 40000.0, rate: 0.07400000000000001 },
    FederalBracket { threshold: 50000.0, rate: 0.087 },
    FederalBracket { threshold: 60000.0, rate: 0.102 },
    FederalBracket { threshold: 70000.0, rate: 0.115 },
    FederalBracket { threshold: 80000.0, rate: 0.13 },
    FederalBracket { threshold: 90000.0, rate: 0.133 },
    FederalBracket { threshold: 100000.0, rate: 0.135 },
    FederalBracket { threshold: 200000.0, rate: 0.14 },
];

/// Simple-tax scale for canton VS, married taxpayer.
/// The canton publishes one shared scale; this is the same table
/// for both marital statuses.
pub const VS_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.02 },
    FederalBracket { threshold: 5000.0, rate: 0.02 },
    FederalBracket { threshold: 10000.0, rate: 0.027999999999999997 },
    FederalBracket { threshold: 20000.0, rate: 0.046 },
    FederalBracket { threshold: 30000.0, rate: 0.06 },
    FederalBracket { threshold: 40000.0, rate: 0.07400000000000001 },
    FederalBracket { threshold: 50000.0, rate: 0.087 },
    FederalBracket { threshold: 60000.0, rate: 0.102 },
    FederalBracket { threshold: 70000.0, rate: 0.115 },
    FederalBracket { threshold: 80000.0, rate: 0.13 },
    FederalBracket { threshold: 90000.0, rate: 0.133 },
    FederalBracket { threshold: 100000.0, rate: 0.135 },
    FederalBracket { threshold: 200000.0, rate: 0.14 },
];

/// Simple-tax scale for canton ZG, single taxpayer.
pub const ZG_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.005 },
    FederalBracket { threshold: 1100.0, rate: 0.01 },
    FederalBracket { threshold: 3300.0, rate: 0.02 },
    FederalBracket { threshold: 6100.0, rate: 0.03 },
    FederalBracket { threshold: 10100.0, rate: 0.0325 },
    FederalBracket { threshold: 15300.0, rate: 0.035 },
    FederalBracket { threshold: 21100.0, rate: 0.04 },
    FederalBracket { threshold: 26900.0, rate: 0.045 },
    FederalBracket { threshold: 34900.0, rate: 0.055 },
    FederalBracket { threshold: 46400.0, rate: 0.055 },
    FederalBracket { threshold: 59700.0, rate: 0.065 },
    FederalBracket { threshold: 74700.0, rate: 0.08 },
    FederalBracket { threshold: 94800.0, rate: 0.1 },
    FederalBracket { threshold: 120100.0, rate: 0.09 },
    FederalBracket { threshold: 149900.0, rate: 0.08 },
];

/// Simple-tax scale for canton ZG, married taxpayer.
pub const ZG_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.005 },
    FederalBracket { threshold: 2200.0, rate: 0.01 },
    FederalBracket { threshold: 6600.0, rate: 0.02 },
    FederalBracket { threshold: 12200.0, rate: 0.03 },
    FederalBracket { threshold: 20200.0, rate: 0.0325 },
    FederalBracket { threshold: 30600.0, rate: 0.035 },
    FederalBracket { threshold: 42200.0, rate: 0.04 },
    FederalBracket { threshold: 53800.0, rate: 0.045 },
    FederalBracket { threshold: 69800.0, rate: 0.055 },
    FederalBracket { threshold: 92800.0, rate: 0.055 },
    FederalBracket { threshold: 119400.0, rate: 0.065 },
    FederalBracket { threshold: 149400.0, rate: 0.08 },
    FederalBracket { threshold: 189600.0, rate: 0.1 },
    FederalBracket { threshold: 240200.0, rate: 0.09 },
    FederalBracket { threshold: 299800.0, rate: 0.08 },
];

/// Simple-tax scale for canton ZH, single taxpayer.
pub const ZH_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 7000.0, rate: 0.02 },
    FederalBracket { threshold: 12000.0, rate: 0.03 },
    FederalBracket { threshold: 16800.0, rate: 0.04 },
    FederalBracket { threshold: 24800.0, rate: 0.05 },
    FederalBracket { threshold: 34500.0, rate: 0.06 },
    FederalBracket { threshold: 45700.0, rate: 0.07 },
    FederalBracket { threshold: 58800.0, rate: 0.08 },
    FederalBracket { threshold: 76400.0, rate: 0.09 },
    FederalBracket { threshold: 110400.0, rate: 0.1 },
    FederalBracket { threshold: 144100.0, rate: 0.11 },
    FederalBracket { threshold: 197400.0, rate: 0.12 },
    FederalBracket { threshold: 266700.0, rate: 0.13 },
];

/// Simple-tax scale for canton ZH, married taxpayer.
pub const ZH_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 14100.0, rate: 0.02 },
    FederalBracket { threshold: 20500.0, rate: 0.03 },
    FederalBracket { threshold: 28600.0, rate: 0.04 },
    FederalBracket { threshold: 38400.0, rate: 0.05 },
    FederalBracket { threshold: 49600.0, rate: 0.06 },
    FederalBracket { threshold: 64100.0, rate: 0.07 },
    FederalBracket { threshold: 96300.0, rate: 0.08 },
    FederalBracket { threshold: 128700.0, rate: 0.09 },
    FederalBracket { threshold: 177200.0, rate: 0.1 },
    FederalBracket { threshold: 235100.0, rate: 0.11 },
    FederalBracket { threshold: 298000.0, rate: 0.12 },
    FederalBracket { threshold: 370600.0, rate: 0.13 },
];

/// Every imported scale.
pub const BASE_SCALES: &[BaseScale] = &[
    BaseScale {
        canton_code: "AG",
        splitting_factor_married: Some(2.0),
        single: AG_SINGLE_BRACKETS,
        married: AG_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "AI",
        splitting_factor_married: Some(2.0),
        single: AI_SINGLE_BRACKETS,
        married: AI_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "AR",
        splitting_factor_married: None,
        single: AR_SINGLE_BRACKETS,
        married: AR_MARRIED_BRACKETS,
        shared_scale: false,
        subjects: &["Alleinstehend ohne Kinder", "Verheiratet / Alleinstehend mit Kindern"],
    },
    BaseScale {
        canton_code: "BS",
        splitting_factor_married: None,
        single: BS_SINGLE_BRACKETS,
        married: BS_MARRIED_BRACKETS,
        shared_scale: false,
        subjects: &["Alleinstehend ohne Kinder", "Verheiratet / Alleinstehend mit Kindern"],
    },
    BaseScale {
        canton_code: "FR",
        splitting_factor_married: None,
        single: FR_SINGLE_BRACKETS,
        married: FR_MARRIED_BRACKETS,
        shared_scale: false,
        subjects: &["Alleinstehend ohne Kinder", "Verheiratet / Alleinstehend mit Kindern"],
    },
    BaseScale {
        canton_code: "GE",
        splitting_factor_married: Some(2.0),
        single: GE_SINGLE_BRACKETS,
        married: GE_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "GL",
        splitting_factor_married: Some(1.7),
        single: GL_SINGLE_BRACKETS,
        married: GL_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "GR",
        splitting_factor_married: Some(1.9),
        single: GR_SINGLE_BRACKETS,
        married: GR_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "JU",
        splitting_factor_married: None,
        single: JU_SINGLE_BRACKETS,
        married: JU_MARRIED_BRACKETS,
        shared_scale: false,
        subjects: &["Alleinstehend mit Kindern im Konkubinat", "Verheiratet / Alleinstehend mit Kindern (nicht im Konkubinat)"],
    },
    BaseScale {
        canton_code: "LU",
        splitting_factor_married: None,
        single: LU_SINGLE_BRACKETS,
        married: LU_MARRIED_BRACKETS,
        shared_scale: false,
        subjects: &["Alleinstehend ohne Kinder", "Verheiratet / Alleinstehend mit Kindern"],
    },
    BaseScale {
        canton_code: "NE",
        splitting_factor_married: Some(1.9230769230769231),
        single: NE_SINGLE_BRACKETS,
        married: NE_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "NW",
        splitting_factor_married: Some(1.85),
        single: NW_SINGLE_BRACKETS,
        married: NW_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "SG",
        splitting_factor_married: Some(2.0),
        single: SG_SINGLE_BRACKETS,
        married: SG_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "SH",
        splitting_factor_married: Some(1.9),
        single: SH_SINGLE_BRACKETS,
        married: SH_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "SO",
        splitting_factor_married: Some(1.9),
        single: SO_SINGLE_BRACKETS,
        married: SO_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "SZ",
        splitting_factor_married: None,
        single: SZ_SINGLE_BRACKETS,
        married: SZ_MARRIED_BRACKETS,
        shared_scale: false,
        subjects: &["Alleinstehend", "Verheiratet"],
    },
    BaseScale {
        canton_code: "TG",
        splitting_factor_married: Some(2.0),
        single: TG_SINGLE_BRACKETS,
        married: TG_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "TI",
        splitting_factor_married: None,
        single: TI_SINGLE_BRACKETS,
        married: TI_MARRIED_BRACKETS,
        shared_scale: false,
        subjects: &["Alleinstehend ohne Kinder", "Verheiratet / Alleinstehend mit Kindern"],
    },
    BaseScale {
        canton_code: "VD",
        splitting_factor_married: None,
        single: VD_SINGLE_BRACKETS,
        married: VD_MARRIED_BRACKETS,
        shared_scale: false,
        subjects: &["Alleinstehend mit / ohne Kinder", "Verheiratet"],
    },
    BaseScale {
        canton_code: "VS",
        splitting_factor_married: Some(0.0),
        single: VS_SINGLE_BRACKETS,
        married: VS_MARRIED_BRACKETS,
        shared_scale: true,
        subjects: &["Alle"],
    },
    BaseScale {
        canton_code: "ZG",
        splitting_factor_married: None,
        single: ZG_SINGLE_BRACKETS,
        married: ZG_MARRIED_BRACKETS,
        shared_scale: false,
        subjects: &["Alleinstehend ohne Kinder", "Verheiratet / Alleinstehend mit Kindern"],
    },
    BaseScale {
        canton_code: "ZH",
        splitting_factor_married: None,
        single: ZH_SINGLE_BRACKETS,
        married: ZH_MARRIED_BRACKETS,
        shared_scale: false,
        subjects: &["Alleinstehend ohne Kinder", "Verheiratet / Alleinstehend mit Kindern"],
    },
];

/// Look up an imported scale by canton code.
pub fn base_scale(canton_code: &str) -> Option<&'static BaseScale> {
    BASE_SCALES.iter().find(|s| s.canton_code == canton_code)
}
