// Life Optimizer
// Copyright (C) 2026 MILAN NIKOLIC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! Cantonal simple-tax scales imported from ESTV "Tarife" exports.
//!
//! GENERATED by `tools/import_estv_scales.py` -- do not edit by hand;
//! re-run the importer instead.
//!
//! Source: `estv_scales_AG.xlsx`, exported from the ESTV tax
//! calculator's Tarife section.
//!
//! `threshold` is the income level at which the band begins and `rate` is
//! that band's marginal rate as a fraction. The ESTV export expresses the
//! same schedule as band *widths* ("Für die nächsten CHF"); the importer
//! accumulates those widths into thresholds, which is an exact conversion
//! for the marginal structure.

use crate::federal_tax::FederalBracket;

/// One canton's imported simple-tax scale.
#[derive(Debug, Clone, Copy)]
pub struct BaseScale {
    pub canton_code: &'static str,
    /// Income-splitting divisor, if the canton uses splitting.
    pub splitting_factor: Option<f64>,
    /// Marginal bands as (threshold, rate fraction).
    pub brackets: &'static [FederalBracket],
    /// The `Steuersubjekt` values present in the export, so an unexpected
    /// subject split is visible rather than silently merged.
    pub subjects: &'static [&'static str],
}

/// Simple-tax scale for canton AG (Export).
/// Steuersubjekt values in the export: Alle.
pub const AG_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 4300.0, rate: 0.01 },
    FederalBracket { threshold: 8100.0, rate: 0.02 },
    FederalBracket { threshold: 12000.0, rate: 0.03 },
    FederalBracket { threshold: 16200.0, rate: 0.04 },
    FederalBracket { threshold: 20500.0, rate: 0.05 },
    FederalBracket { threshold: 25700.0, rate: 0.06 },
    FederalBracket { threshold: 33100.0, rate: 0.07 },
    FederalBracket { threshold: 41700.0, rate: 0.08 },
    FederalBracket { threshold: 51300.0, rate: 0.085 },
    FederalBracket { threshold: 63100.0, rate: 0.09 },
    FederalBracket { threshold: 74800.0, rate: 0.095 },
    FederalBracket { threshold: 110100.0, rate: 0.1 },
    FederalBracket { threshold: 176400.0, rate: 0.105 },
    FederalBracket { threshold: 352700.0, rate: 0.11 },
];

/// Every imported scale.
pub const BASE_SCALES: &[BaseScale] = &[
    BaseScale {
        canton_code: "AG",
        splitting_factor: Some(2.0),
        brackets: AG_BRACKETS,
        subjects: &["Alle"],
    },
];

/// Look up an imported scale by canton code.
pub fn base_scale(canton_code: &str) -> Option<&'static BaseScale> {
    BASE_SCALES.iter().find(|s| s.canton_code == canton_code)
}
