// Life Optimizer
// Copyright (C) 2026 MILAN NIKOLIC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! Official federal direct-tax tariff (direkte Bundessteuer),
//! imported from the ESTV Tarife export `estv_scales_Bund.xlsx`.
//!
//! GENERATED by `tools/import_estv_scales.py` -- do not edit by hand.
//!
//! This is the authoritative published tariff, replacing an earlier
//! hand-entered table whose top marginal rate was 7.39% against the
//! statutory 13.2%, and which contained a non-monotonic segment.
//!
//! `threshold` is the income at which the band begins and `rate` is that
//! band's marginal rate as a fraction.

use crate::federal_tax::FederalBracket;

/// Federal tariff, single taxpayer.
pub const FEDERAL_SINGLE_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 15200.0, rate: 0.0077 },
    FederalBracket { threshold: 33200.0, rate: 0.0088 },
    FederalBracket { threshold: 43500.0, rate: 0.0264 },
    FederalBracket { threshold: 58000.0, rate: 0.029699999999999997 },
    FederalBracket { threshold: 76100.0, rate: 0.059399999999999994 },
    FederalBracket { threshold: 82000.0, rate: 0.066 },
    FederalBracket { threshold: 108800.0, rate: 0.08800000000000001 },
    FederalBracket { threshold: 141500.0, rate: 0.11 },
    FederalBracket { threshold: 184900.0, rate: 0.132 },
    FederalBracket { threshold: 793300.0, rate: 0.132 },
    FederalBracket { threshold: 793400.0, rate: 0.115 },
];

/// Federal tariff, married taxpayer.
pub const FEDERAL_MARRIED_BRACKETS: &[FederalBracket] = &[
    FederalBracket { threshold: 0.0, rate: 0.0 },
    FederalBracket { threshold: 29700.0, rate: 0.01 },
    FederalBracket { threshold: 53400.0, rate: 0.02 },
    FederalBracket { threshold: 61300.0, rate: 0.03 },
    FederalBracket { threshold: 79100.0, rate: 0.04 },
    FederalBracket { threshold: 94900.0, rate: 0.05 },
    FederalBracket { threshold: 108600.0, rate: 0.06 },
    FederalBracket { threshold: 120500.0, rate: 0.07 },
    FederalBracket { threshold: 130500.0, rate: 0.08 },
    FederalBracket { threshold: 138300.0, rate: 0.09 },
    FederalBracket { threshold: 144200.0, rate: 0.1 },
    FederalBracket { threshold: 148200.0, rate: 0.11 },
    FederalBracket { threshold: 150300.0, rate: 0.12 },
    FederalBracket { threshold: 152300.0, rate: 0.13 },
    FederalBracket { threshold: 940800.0, rate: 0.13 },
    FederalBracket { threshold: 940900.0, rate: 0.115 },
];
